trigger:
- main
pool:
  vmImage: ubuntu-latest
variables:
  - group: PoC-MC
jobs:
  - job: Sync
    steps:
    - checkout: self
      persistCredentials: true
    - pwsh: |
        $sourceURL = "https://$(GITPAT)@$(GITREPO)"
        git remote add github $sourceURL
        git remote show
        git remote show github
        git checkout main
        git fetch github main
        git pull github main
        git push origin
      displayName: Sync repos
